

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: phonebook
  pool: 20
  username: <%= ENV['USER'] == 'root' ? ENV['SUDO_USER'] : ENV['USER'] %>
  password: harry
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: phonebook_test
  pool: 20
  username: <%= ENV['USER'] == 'root' ? ENV['SUDO_USER'] : ENV['USER'] %>
  password: harry
  host: localhost

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: 'phonebook_staging'
#   pool: 20
#   username: rails_dev
#   password: Welcome@1234
#   host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  database: 'phonebook_staging'
  pool: 20
  username: rails_dev
  password: Welcome@1234
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: 'cpqulvrn'
  pool: 20
  username: cpqulvrn
  password: NY17_XCc9lyMxu6y1bM7eoJgukB_tWes
  host: ruby.db.elephantsql.com

  #database: blog_production
  #username: myapp
  #password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  #host:
  #port:
