

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: sg_development
#   pool: 20
#   username: <%= ENV['USER'] == 'root' ? ENV['SUDO_USER'] : ENV['USER'] %>
#   password: harry
#   host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: 'phonebook_staging'
  pool: 20
  username: rails_dev
  password: Welcome@1234
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: 'phonebook_production'
  pool: 20
  username: rails_dev
  password: Welcome@1234
  host: localhost

  #database: blog_production
  #username: myapp
  #password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  #host:
  #port:
